// Generated by view binder compiler. Do not edit!
package com.example.usersidelab.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.usersidelab.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityDisplayprojectdetailPageBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final LinearLayout containerproject;

  @NonNull
  public final TextView displayprojectdetails;

  @NonNull
  public final TextView displayprojectname;

  @NonNull
  public final TextView displayurl;

  @NonNull
  public final TextView skillsused;

  private ActivityDisplayprojectdetailPageBinding(@NonNull ConstraintLayout rootView,
      @NonNull LinearLayout containerproject, @NonNull TextView displayprojectdetails,
      @NonNull TextView displayprojectname, @NonNull TextView displayurl,
      @NonNull TextView skillsused) {
    this.rootView = rootView;
    this.containerproject = containerproject;
    this.displayprojectdetails = displayprojectdetails;
    this.displayprojectname = displayprojectname;
    this.displayurl = displayurl;
    this.skillsused = skillsused;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityDisplayprojectdetailPageBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityDisplayprojectdetailPageBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_displayprojectdetail_page, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityDisplayprojectdetailPageBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.containerproject;
      LinearLayout containerproject = ViewBindings.findChildViewById(rootView, id);
      if (containerproject == null) {
        break missingId;
      }

      id = R.id.displayprojectdetails;
      TextView displayprojectdetails = ViewBindings.findChildViewById(rootView, id);
      if (displayprojectdetails == null) {
        break missingId;
      }

      id = R.id.displayprojectname;
      TextView displayprojectname = ViewBindings.findChildViewById(rootView, id);
      if (displayprojectname == null) {
        break missingId;
      }

      id = R.id.displayurl;
      TextView displayurl = ViewBindings.findChildViewById(rootView, id);
      if (displayurl == null) {
        break missingId;
      }

      id = R.id.skillsused;
      TextView skillsused = ViewBindings.findChildViewById(rootView, id);
      if (skillsused == null) {
        break missingId;
      }

      return new ActivityDisplayprojectdetailPageBinding((ConstraintLayout) rootView,
          containerproject, displayprojectdetails, displayprojectname, displayurl, skillsused);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
