// Generated by view binder compiler. Do not edit!
package com.example.usersidelab.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.usersidelab.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityChomepageBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final Button add;

  @NonNull
  public final ScrollView drawerLayout;

  @NonNull
  public final LinearLayout linearLayout2;

  @NonNull
  public final Button logout;

  @NonNull
  public final RecyclerView userRecycleView;

  private ActivityChomepageBinding(@NonNull ScrollView rootView, @NonNull Button add,
      @NonNull ScrollView drawerLayout, @NonNull LinearLayout linearLayout2, @NonNull Button logout,
      @NonNull RecyclerView userRecycleView) {
    this.rootView = rootView;
    this.add = add;
    this.drawerLayout = drawerLayout;
    this.linearLayout2 = linearLayout2;
    this.logout = logout;
    this.userRecycleView = userRecycleView;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityChomepageBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityChomepageBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_chomepage, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityChomepageBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.add;
      Button add = ViewBindings.findChildViewById(rootView, id);
      if (add == null) {
        break missingId;
      }

      ScrollView drawerLayout = (ScrollView) rootView;

      id = R.id.linearLayout2;
      LinearLayout linearLayout2 = ViewBindings.findChildViewById(rootView, id);
      if (linearLayout2 == null) {
        break missingId;
      }

      id = R.id.logout;
      Button logout = ViewBindings.findChildViewById(rootView, id);
      if (logout == null) {
        break missingId;
      }

      id = R.id.userRecycleView;
      RecyclerView userRecycleView = ViewBindings.findChildViewById(rootView, id);
      if (userRecycleView == null) {
        break missingId;
      }

      return new ActivityChomepageBinding((ScrollView) rootView, add, drawerLayout, linearLayout2,
          logout, userRecycleView);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
