// Generated by view binder compiler. Do not edit!
package com.example.companylab.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.companylab.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityRegistrationDetailsBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button backbutton;

  @NonNull
  public final Button signupbutton;

  @NonNull
  public final EditText signupuseremail;

  @NonNull
  public final EditText signupusername;

  @NonNull
  public final EditText signupuserpassword;

  @NonNull
  public final TextView textView2;

  private ActivityRegistrationDetailsBinding(@NonNull ConstraintLayout rootView,
      @NonNull Button backbutton, @NonNull Button signupbutton, @NonNull EditText signupuseremail,
      @NonNull EditText signupusername, @NonNull EditText signupuserpassword,
      @NonNull TextView textView2) {
    this.rootView = rootView;
    this.backbutton = backbutton;
    this.signupbutton = signupbutton;
    this.signupuseremail = signupuseremail;
    this.signupusername = signupusername;
    this.signupuserpassword = signupuserpassword;
    this.textView2 = textView2;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityRegistrationDetailsBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityRegistrationDetailsBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_registration_details, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityRegistrationDetailsBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.backbutton;
      Button backbutton = ViewBindings.findChildViewById(rootView, id);
      if (backbutton == null) {
        break missingId;
      }

      id = R.id.signupbutton;
      Button signupbutton = ViewBindings.findChildViewById(rootView, id);
      if (signupbutton == null) {
        break missingId;
      }

      id = R.id.signupuseremail;
      EditText signupuseremail = ViewBindings.findChildViewById(rootView, id);
      if (signupuseremail == null) {
        break missingId;
      }

      id = R.id.signupusername;
      EditText signupusername = ViewBindings.findChildViewById(rootView, id);
      if (signupusername == null) {
        break missingId;
      }

      id = R.id.signupuserpassword;
      EditText signupuserpassword = ViewBindings.findChildViewById(rootView, id);
      if (signupuserpassword == null) {
        break missingId;
      }

      id = R.id.textView2;
      TextView textView2 = ViewBindings.findChildViewById(rootView, id);
      if (textView2 == null) {
        break missingId;
      }

      return new ActivityRegistrationDetailsBinding((ConstraintLayout) rootView, backbutton,
          signupbutton, signupuseremail, signupusername, signupuserpassword, textView2);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
