// Generated by view binder compiler. Do not edit!
package com.example.usersidelab.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.usersidelab.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityApplicantDetailsPageBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final Button accept;

  @NonNull
  public final Button backbutton;

  @NonNull
  public final TextView displayapplicantemail;

  @NonNull
  public final TextView displayapplicantname;

  @NonNull
  public final Button reject;

  @NonNull
  public final RecyclerView userRecycleVieweducation;

  @NonNull
  public final RecyclerView userRecycleViewexperience;

  @NonNull
  public final RecyclerView userRecycleViewproject;

  private ActivityApplicantDetailsPageBinding(@NonNull ScrollView rootView, @NonNull Button accept,
      @NonNull Button backbutton, @NonNull TextView displayapplicantemail,
      @NonNull TextView displayapplicantname, @NonNull Button reject,
      @NonNull RecyclerView userRecycleVieweducation,
      @NonNull RecyclerView userRecycleViewexperience,
      @NonNull RecyclerView userRecycleViewproject) {
    this.rootView = rootView;
    this.accept = accept;
    this.backbutton = backbutton;
    this.displayapplicantemail = displayapplicantemail;
    this.displayapplicantname = displayapplicantname;
    this.reject = reject;
    this.userRecycleVieweducation = userRecycleVieweducation;
    this.userRecycleViewexperience = userRecycleViewexperience;
    this.userRecycleViewproject = userRecycleViewproject;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityApplicantDetailsPageBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityApplicantDetailsPageBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_applicant_details_page, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityApplicantDetailsPageBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.accept;
      Button accept = ViewBindings.findChildViewById(rootView, id);
      if (accept == null) {
        break missingId;
      }

      id = R.id.backbutton;
      Button backbutton = ViewBindings.findChildViewById(rootView, id);
      if (backbutton == null) {
        break missingId;
      }

      id = R.id.displayapplicantemail;
      TextView displayapplicantemail = ViewBindings.findChildViewById(rootView, id);
      if (displayapplicantemail == null) {
        break missingId;
      }

      id = R.id.displayapplicantname;
      TextView displayapplicantname = ViewBindings.findChildViewById(rootView, id);
      if (displayapplicantname == null) {
        break missingId;
      }

      id = R.id.reject;
      Button reject = ViewBindings.findChildViewById(rootView, id);
      if (reject == null) {
        break missingId;
      }

      id = R.id.userRecycleVieweducation;
      RecyclerView userRecycleVieweducation = ViewBindings.findChildViewById(rootView, id);
      if (userRecycleVieweducation == null) {
        break missingId;
      }

      id = R.id.userRecycleViewexperience;
      RecyclerView userRecycleViewexperience = ViewBindings.findChildViewById(rootView, id);
      if (userRecycleViewexperience == null) {
        break missingId;
      }

      id = R.id.userRecycleViewproject;
      RecyclerView userRecycleViewproject = ViewBindings.findChildViewById(rootView, id);
      if (userRecycleViewproject == null) {
        break missingId;
      }

      return new ActivityApplicantDetailsPageBinding((ScrollView) rootView, accept, backbutton,
          displayapplicantemail, displayapplicantname, reject, userRecycleVieweducation,
          userRecycleViewexperience, userRecycleViewproject);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
