// Generated by view binder compiler. Do not edit!
package com.example.companylab.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.companylab.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityCompanydetailPageBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final EditText address;

  @NonNull
  public final Button backbutton;

  @NonNull
  public final EditText cname;

  @NonNull
  public final EditText companydes;

  @NonNull
  public final EditText contact;

  @NonNull
  public final LinearLayout container;

  @NonNull
  public final Button experiencesave;

  @NonNull
  public final TextView textView2;

  private ActivityCompanydetailPageBinding(@NonNull ScrollView rootView, @NonNull EditText address,
      @NonNull Button backbutton, @NonNull EditText cname, @NonNull EditText companydes,
      @NonNull EditText contact, @NonNull LinearLayout container, @NonNull Button experiencesave,
      @NonNull TextView textView2) {
    this.rootView = rootView;
    this.address = address;
    this.backbutton = backbutton;
    this.cname = cname;
    this.companydes = companydes;
    this.contact = contact;
    this.container = container;
    this.experiencesave = experiencesave;
    this.textView2 = textView2;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityCompanydetailPageBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityCompanydetailPageBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_companydetail_page, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityCompanydetailPageBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.address;
      EditText address = ViewBindings.findChildViewById(rootView, id);
      if (address == null) {
        break missingId;
      }

      id = R.id.backbutton;
      Button backbutton = ViewBindings.findChildViewById(rootView, id);
      if (backbutton == null) {
        break missingId;
      }

      id = R.id.cname;
      EditText cname = ViewBindings.findChildViewById(rootView, id);
      if (cname == null) {
        break missingId;
      }

      id = R.id.companydes;
      EditText companydes = ViewBindings.findChildViewById(rootView, id);
      if (companydes == null) {
        break missingId;
      }

      id = R.id.contact;
      EditText contact = ViewBindings.findChildViewById(rootView, id);
      if (contact == null) {
        break missingId;
      }

      id = R.id.container;
      LinearLayout container = ViewBindings.findChildViewById(rootView, id);
      if (container == null) {
        break missingId;
      }

      id = R.id.experiencesave;
      Button experiencesave = ViewBindings.findChildViewById(rootView, id);
      if (experiencesave == null) {
        break missingId;
      }

      id = R.id.textView2;
      TextView textView2 = ViewBindings.findChildViewById(rootView, id);
      if (textView2 == null) {
        break missingId;
      }

      return new ActivityCompanydetailPageBinding((ScrollView) rootView, address, backbutton, cname,
          companydes, contact, container, experiencesave, textView2);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
