// Generated by view binder compiler. Do not edit!
package com.example.companylab.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.RelativeLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.Toolbar;
import androidx.drawerlayout.widget.DrawerLayout;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.companylab.R;
import com.google.android.material.navigation.NavigationView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityHomepageBinding implements ViewBinding {
  @NonNull
  private final DrawerLayout rootView;

  @NonNull
  public final NavigationView NavDrawer;

  @NonNull
  public final Button addButton;

  @NonNull
  public final DrawerLayout drawerLayout;

  @NonNull
  public final RelativeLayout relativeLayout;

  @NonNull
  public final Toolbar toolbar;

  @NonNull
  public final RecyclerView userRecycleView;

  private ActivityHomepageBinding(@NonNull DrawerLayout rootView, @NonNull NavigationView NavDrawer,
      @NonNull Button addButton, @NonNull DrawerLayout drawerLayout,
      @NonNull RelativeLayout relativeLayout, @NonNull Toolbar toolbar,
      @NonNull RecyclerView userRecycleView) {
    this.rootView = rootView;
    this.NavDrawer = NavDrawer;
    this.addButton = addButton;
    this.drawerLayout = drawerLayout;
    this.relativeLayout = relativeLayout;
    this.toolbar = toolbar;
    this.userRecycleView = userRecycleView;
  }

  @Override
  @NonNull
  public DrawerLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityHomepageBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityHomepageBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_homepage, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityHomepageBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.Nav_drawer;
      NavigationView NavDrawer = ViewBindings.findChildViewById(rootView, id);
      if (NavDrawer == null) {
        break missingId;
      }

      id = R.id.addButton;
      Button addButton = ViewBindings.findChildViewById(rootView, id);
      if (addButton == null) {
        break missingId;
      }

      DrawerLayout drawerLayout = (DrawerLayout) rootView;

      id = R.id.relativeLayout;
      RelativeLayout relativeLayout = ViewBindings.findChildViewById(rootView, id);
      if (relativeLayout == null) {
        break missingId;
      }

      id = R.id.toolbar;
      Toolbar toolbar = ViewBindings.findChildViewById(rootView, id);
      if (toolbar == null) {
        break missingId;
      }

      id = R.id.userRecycleView;
      RecyclerView userRecycleView = ViewBindings.findChildViewById(rootView, id);
      if (userRecycleView == null) {
        break missingId;
      }

      return new ActivityHomepageBinding((DrawerLayout) rootView, NavDrawer, addButton,
          drawerLayout, relativeLayout, toolbar, userRecycleView);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
