// Generated by view binder compiler. Do not edit!
package com.example.usersidelab.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.usersidelab.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityDisplayexperiencedetailPageBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final LinearLayout containerexperience;

  @NonNull
  public final TextView displayexperiencecompanybame;

  @NonNull
  public final TextView experiencededignation;

  @NonNull
  public final TextView totalwokexperience;

  private ActivityDisplayexperiencedetailPageBinding(@NonNull ConstraintLayout rootView,
      @NonNull LinearLayout containerexperience, @NonNull TextView displayexperiencecompanybame,
      @NonNull TextView experiencededignation, @NonNull TextView totalwokexperience) {
    this.rootView = rootView;
    this.containerexperience = containerexperience;
    this.displayexperiencecompanybame = displayexperiencecompanybame;
    this.experiencededignation = experiencededignation;
    this.totalwokexperience = totalwokexperience;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityDisplayexperiencedetailPageBinding inflate(
      @NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityDisplayexperiencedetailPageBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_displayexperiencedetail_page, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityDisplayexperiencedetailPageBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.containerexperience;
      LinearLayout containerexperience = ViewBindings.findChildViewById(rootView, id);
      if (containerexperience == null) {
        break missingId;
      }

      id = R.id.displayexperiencecompanybame;
      TextView displayexperiencecompanybame = ViewBindings.findChildViewById(rootView, id);
      if (displayexperiencecompanybame == null) {
        break missingId;
      }

      id = R.id.experiencededignation;
      TextView experiencededignation = ViewBindings.findChildViewById(rootView, id);
      if (experiencededignation == null) {
        break missingId;
      }

      id = R.id.totalwokexperience;
      TextView totalwokexperience = ViewBindings.findChildViewById(rootView, id);
      if (totalwokexperience == null) {
        break missingId;
      }

      return new ActivityDisplayexperiencedetailPageBinding((ConstraintLayout) rootView,
          containerexperience, displayexperiencecompanybame, experiencededignation,
          totalwokexperience);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
