// Generated by view binder compiler. Do not edit!
package com.example.usersidelab.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.usersidelab.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityExperienceDetailPageBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final Button addButton;

  @NonNull
  public final Button backbutton;

  @NonNull
  public final LinearLayout container;

  @NonNull
  public final EditText experiencecompanybame;

  @NonNull
  public final EditText experiencededignation;

  @NonNull
  public final Button experiencesave;

  @NonNull
  public final TextView textView2;

  @NonNull
  public final EditText totalwokexperience;

  @NonNull
  public final EditText working;

  private ActivityExperienceDetailPageBinding(@NonNull ScrollView rootView,
      @NonNull Button addButton, @NonNull Button backbutton, @NonNull LinearLayout container,
      @NonNull EditText experiencecompanybame, @NonNull EditText experiencededignation,
      @NonNull Button experiencesave, @NonNull TextView textView2,
      @NonNull EditText totalwokexperience, @NonNull EditText working) {
    this.rootView = rootView;
    this.addButton = addButton;
    this.backbutton = backbutton;
    this.container = container;
    this.experiencecompanybame = experiencecompanybame;
    this.experiencededignation = experiencededignation;
    this.experiencesave = experiencesave;
    this.textView2 = textView2;
    this.totalwokexperience = totalwokexperience;
    this.working = working;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityExperienceDetailPageBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityExperienceDetailPageBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_experience_detail_page, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityExperienceDetailPageBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.addButton;
      Button addButton = ViewBindings.findChildViewById(rootView, id);
      if (addButton == null) {
        break missingId;
      }

      id = R.id.backbutton;
      Button backbutton = ViewBindings.findChildViewById(rootView, id);
      if (backbutton == null) {
        break missingId;
      }

      id = R.id.container;
      LinearLayout container = ViewBindings.findChildViewById(rootView, id);
      if (container == null) {
        break missingId;
      }

      id = R.id.experiencecompanybame;
      EditText experiencecompanybame = ViewBindings.findChildViewById(rootView, id);
      if (experiencecompanybame == null) {
        break missingId;
      }

      id = R.id.experiencededignation;
      EditText experiencededignation = ViewBindings.findChildViewById(rootView, id);
      if (experiencededignation == null) {
        break missingId;
      }

      id = R.id.experiencesave;
      Button experiencesave = ViewBindings.findChildViewById(rootView, id);
      if (experiencesave == null) {
        break missingId;
      }

      id = R.id.textView2;
      TextView textView2 = ViewBindings.findChildViewById(rootView, id);
      if (textView2 == null) {
        break missingId;
      }

      id = R.id.totalwokexperience;
      EditText totalwokexperience = ViewBindings.findChildViewById(rootView, id);
      if (totalwokexperience == null) {
        break missingId;
      }

      id = R.id.working;
      EditText working = ViewBindings.findChildViewById(rootView, id);
      if (working == null) {
        break missingId;
      }

      return new ActivityExperienceDetailPageBinding((ScrollView) rootView, addButton, backbutton,
          container, experiencecompanybame, experiencededignation, experiencesave, textView2,
          totalwokexperience, working);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
