// Generated by view binder compiler. Do not edit!
package com.example.companylab.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.companylab.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityStartPageBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button RegisterButton;

  @NonNull
  public final LinearLayout innerlayoutchooseuser;

  @NonNull
  public final LinearLayout layoutchooseuser;

  @NonNull
  public final Button loginButton;

  private ActivityStartPageBinding(@NonNull ConstraintLayout rootView,
      @NonNull Button RegisterButton, @NonNull LinearLayout innerlayoutchooseuser,
      @NonNull LinearLayout layoutchooseuser, @NonNull Button loginButton) {
    this.rootView = rootView;
    this.RegisterButton = RegisterButton;
    this.innerlayoutchooseuser = innerlayoutchooseuser;
    this.layoutchooseuser = layoutchooseuser;
    this.loginButton = loginButton;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityStartPageBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityStartPageBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_start_page, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityStartPageBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.RegisterButton;
      Button RegisterButton = ViewBindings.findChildViewById(rootView, id);
      if (RegisterButton == null) {
        break missingId;
      }

      id = R.id.innerlayoutchooseuser;
      LinearLayout innerlayoutchooseuser = ViewBindings.findChildViewById(rootView, id);
      if (innerlayoutchooseuser == null) {
        break missingId;
      }

      id = R.id.layoutchooseuser;
      LinearLayout layoutchooseuser = ViewBindings.findChildViewById(rootView, id);
      if (layoutchooseuser == null) {
        break missingId;
      }

      id = R.id.loginButton;
      Button loginButton = ViewBindings.findChildViewById(rootView, id);
      if (loginButton == null) {
        break missingId;
      }

      return new ActivityStartPageBinding((ConstraintLayout) rootView, RegisterButton,
          innerlayoutchooseuser, layoutchooseuser, loginButton);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
