// Generated by view binder compiler. Do not edit!
package com.example.usersidelab.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.usersidelab.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityJobDetailsPageBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final Button apply;

  @NonNull
  public final Button backbutton;

  @NonNull
  public final TextView displaycompanycontact;

  @NonNull
  public final TextView displaycompanydetails;

  @NonNull
  public final TextView displaycompanyname;

  @NonNull
  public final TextView displaycomploc;

  @NonNull
  public final TextView displayjobben;

  @NonNull
  public final TextView displayjobcomp;

  @NonNull
  public final TextView displayjobdec;

  @NonNull
  public final TextView displayjobloc;

  @NonNull
  public final TextView displayjobsalary;

  @NonNull
  public final TextView displayjobshift;

  @NonNull
  public final TextView displayjobtitle;

  @NonNull
  public final TextView displayjobtype;

  private ActivityJobDetailsPageBinding(@NonNull ScrollView rootView, @NonNull Button apply,
      @NonNull Button backbutton, @NonNull TextView displaycompanycontact,
      @NonNull TextView displaycompanydetails, @NonNull TextView displaycompanyname,
      @NonNull TextView displaycomploc, @NonNull TextView displayjobben,
      @NonNull TextView displayjobcomp, @NonNull TextView displayjobdec,
      @NonNull TextView displayjobloc, @NonNull TextView displayjobsalary,
      @NonNull TextView displayjobshift, @NonNull TextView displayjobtitle,
      @NonNull TextView displayjobtype) {
    this.rootView = rootView;
    this.apply = apply;
    this.backbutton = backbutton;
    this.displaycompanycontact = displaycompanycontact;
    this.displaycompanydetails = displaycompanydetails;
    this.displaycompanyname = displaycompanyname;
    this.displaycomploc = displaycomploc;
    this.displayjobben = displayjobben;
    this.displayjobcomp = displayjobcomp;
    this.displayjobdec = displayjobdec;
    this.displayjobloc = displayjobloc;
    this.displayjobsalary = displayjobsalary;
    this.displayjobshift = displayjobshift;
    this.displayjobtitle = displayjobtitle;
    this.displayjobtype = displayjobtype;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityJobDetailsPageBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityJobDetailsPageBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_job_details_page, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityJobDetailsPageBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.apply;
      Button apply = ViewBindings.findChildViewById(rootView, id);
      if (apply == null) {
        break missingId;
      }

      id = R.id.backbutton;
      Button backbutton = ViewBindings.findChildViewById(rootView, id);
      if (backbutton == null) {
        break missingId;
      }

      id = R.id.displaycompanycontact;
      TextView displaycompanycontact = ViewBindings.findChildViewById(rootView, id);
      if (displaycompanycontact == null) {
        break missingId;
      }

      id = R.id.displaycompanydetails;
      TextView displaycompanydetails = ViewBindings.findChildViewById(rootView, id);
      if (displaycompanydetails == null) {
        break missingId;
      }

      id = R.id.displaycompanyname;
      TextView displaycompanyname = ViewBindings.findChildViewById(rootView, id);
      if (displaycompanyname == null) {
        break missingId;
      }

      id = R.id.displaycomploc;
      TextView displaycomploc = ViewBindings.findChildViewById(rootView, id);
      if (displaycomploc == null) {
        break missingId;
      }

      id = R.id.displayjobben;
      TextView displayjobben = ViewBindings.findChildViewById(rootView, id);
      if (displayjobben == null) {
        break missingId;
      }

      id = R.id.displayjobcomp;
      TextView displayjobcomp = ViewBindings.findChildViewById(rootView, id);
      if (displayjobcomp == null) {
        break missingId;
      }

      id = R.id.displayjobdec;
      TextView displayjobdec = ViewBindings.findChildViewById(rootView, id);
      if (displayjobdec == null) {
        break missingId;
      }

      id = R.id.displayjobloc;
      TextView displayjobloc = ViewBindings.findChildViewById(rootView, id);
      if (displayjobloc == null) {
        break missingId;
      }

      id = R.id.displayjobsalary;
      TextView displayjobsalary = ViewBindings.findChildViewById(rootView, id);
      if (displayjobsalary == null) {
        break missingId;
      }

      id = R.id.displayjobshift;
      TextView displayjobshift = ViewBindings.findChildViewById(rootView, id);
      if (displayjobshift == null) {
        break missingId;
      }

      id = R.id.displayjobtitle;
      TextView displayjobtitle = ViewBindings.findChildViewById(rootView, id);
      if (displayjobtitle == null) {
        break missingId;
      }

      id = R.id.displayjobtype;
      TextView displayjobtype = ViewBindings.findChildViewById(rootView, id);
      if (displayjobtype == null) {
        break missingId;
      }

      return new ActivityJobDetailsPageBinding((ScrollView) rootView, apply, backbutton,
          displaycompanycontact, displaycompanydetails, displaycompanyname, displaycomploc,
          displayjobben, displayjobcomp, displayjobdec, displayjobloc, displayjobsalary,
          displayjobshift, displayjobtitle, displayjobtype);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
