// Generated by view binder compiler. Do not edit!
package com.example.usersidelab.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.usersidelab.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ApplicantitemBinding implements ViewBinding {
  @NonNull
  private final CardView rootView;

  @NonNull
  public final TextView useritememail;

  @NonNull
  public final TextView useritemname;

  @NonNull
  public final TextView useritemsrno;

  private ApplicantitemBinding(@NonNull CardView rootView, @NonNull TextView useritememail,
      @NonNull TextView useritemname, @NonNull TextView useritemsrno) {
    this.rootView = rootView;
    this.useritememail = useritememail;
    this.useritemname = useritemname;
    this.useritemsrno = useritemsrno;
  }

  @Override
  @NonNull
  public CardView getRoot() {
    return rootView;
  }

  @NonNull
  public static ApplicantitemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ApplicantitemBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.applicantitem, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ApplicantitemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.useritememail;
      TextView useritememail = ViewBindings.findChildViewById(rootView, id);
      if (useritememail == null) {
        break missingId;
      }

      id = R.id.useritemname;
      TextView useritemname = ViewBindings.findChildViewById(rootView, id);
      if (useritemname == null) {
        break missingId;
      }

      id = R.id.useritemsrno;
      TextView useritemsrno = ViewBindings.findChildViewById(rootView, id);
      if (useritemsrno == null) {
        break missingId;
      }

      return new ApplicantitemBinding((CardView) rootView, useritememail, useritemname,
          useritemsrno);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
