// Generated by view binder compiler. Do not edit!
package com.example.usersidelab.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.usersidelab.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ApplicationstatusitemBinding implements ViewBinding {
  @NonNull
  private final CardView rootView;

  @NonNull
  public final TextView itemcompanyname;

  @NonNull
  public final TextView itemjobid;

  @NonNull
  public final TextView itemjobname;

  @NonNull
  public final TextView itemstatus;

  private ApplicationstatusitemBinding(@NonNull CardView rootView,
      @NonNull TextView itemcompanyname, @NonNull TextView itemjobid, @NonNull TextView itemjobname,
      @NonNull TextView itemstatus) {
    this.rootView = rootView;
    this.itemcompanyname = itemcompanyname;
    this.itemjobid = itemjobid;
    this.itemjobname = itemjobname;
    this.itemstatus = itemstatus;
  }

  @Override
  @NonNull
  public CardView getRoot() {
    return rootView;
  }

  @NonNull
  public static ApplicationstatusitemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ApplicationstatusitemBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.applicationstatusitem, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ApplicationstatusitemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.itemcompanyname;
      TextView itemcompanyname = ViewBindings.findChildViewById(rootView, id);
      if (itemcompanyname == null) {
        break missingId;
      }

      id = R.id.itemjobid;
      TextView itemjobid = ViewBindings.findChildViewById(rootView, id);
      if (itemjobid == null) {
        break missingId;
      }

      id = R.id.itemjobname;
      TextView itemjobname = ViewBindings.findChildViewById(rootView, id);
      if (itemjobname == null) {
        break missingId;
      }

      id = R.id.itemstatus;
      TextView itemstatus = ViewBindings.findChildViewById(rootView, id);
      if (itemstatus == null) {
        break missingId;
      }

      return new ApplicationstatusitemBinding((CardView) rootView, itemcompanyname, itemjobid,
          itemjobname, itemstatus);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
