// Generated by view binder compiler. Do not edit!
package com.example.usersidelab.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.usersidelab.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ProjectdetailitemBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final LinearLayout container;

  @NonNull
  public final EditText projectdetails;

  @NonNull
  public final EditText projectname;

  @NonNull
  public final EditText skillsused;

  @NonNull
  public final EditText url;

  private ProjectdetailitemBinding(@NonNull ConstraintLayout rootView,
      @NonNull LinearLayout container, @NonNull EditText projectdetails,
      @NonNull EditText projectname, @NonNull EditText skillsused, @NonNull EditText url) {
    this.rootView = rootView;
    this.container = container;
    this.projectdetails = projectdetails;
    this.projectname = projectname;
    this.skillsused = skillsused;
    this.url = url;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ProjectdetailitemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ProjectdetailitemBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.projectdetailitem, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ProjectdetailitemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.container;
      LinearLayout container = ViewBindings.findChildViewById(rootView, id);
      if (container == null) {
        break missingId;
      }

      id = R.id.projectdetails;
      EditText projectdetails = ViewBindings.findChildViewById(rootView, id);
      if (projectdetails == null) {
        break missingId;
      }

      id = R.id.projectname;
      EditText projectname = ViewBindings.findChildViewById(rootView, id);
      if (projectname == null) {
        break missingId;
      }

      id = R.id.skillsused;
      EditText skillsused = ViewBindings.findChildViewById(rootView, id);
      if (skillsused == null) {
        break missingId;
      }

      id = R.id.url;
      EditText url = ViewBindings.findChildViewById(rootView, id);
      if (url == null) {
        break missingId;
      }

      return new ProjectdetailitemBinding((ConstraintLayout) rootView, container, projectdetails,
          projectname, skillsused, url);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
